# The name of connection profile
name: "Org1 Client"
version: "1.0"

# Client section is for NodeJS SDK. 
client:
  organization: org1 # The org that this app instance belong to
  # set connection timeouts for the peer and orderer for the client
  connection:
    timeout:
      peer:
        # the timeout in seconds to be used on requests to a peer,
        # for example sendTransactionProposal
        endorser: 120
        # the timeout in seconds to be used by applications when waiting for an
        # event to occur. This time should be used in a javascript timer object
        # that will cancel the event registration with the event hub instance.
        eventHub: 60
        # the timeout in seconds to be used when setting up the connection
        # with the peers event hub. If the peer does not acknowledge the
        # connection within the time, the application will be notified over the
        # error callback if provided.
        eventReg: 30
      # the timeout in seconds to be used on request to the orderer,
      # for example
      orderer: 30
  credentialStore: # KVS of Client instance
    path: "/tmp/hfc-kvs/org1"
    cryptoStore: # Cryptosuite store of Client instance
      path: "/tmp/hfc-cvs/org1"

# Optinal. But most app would have this so that channle objects can be constructed based on this section.
channels:

  deevochannel: # name of channel
    orderers:
      - orderer1.org0.deevo.io
    peers:
      peer1.org1.deevo.io:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer1.org2.deevo.io:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer1.org3.deevo.io:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer1.org4.deevo.io:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer1.org5.deevo.io:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

  aimthaichannel: # name of channel
    orderers:
      - orderer1.org0.deevo.io
    peers:
      peer1.org1.deevo.io:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer1.org2.deevo.io:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer1.org3.deevo.io:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer1.org4.deevo.io:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer1.org5.deevo.io:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

organizations:
  org1:
    mspid: org1MSP
    peers: 
      - peer1.org1.deevo.io
    certificateAuthorities:
      - rca.org1.deevo.io
    adminPrivateKey:
      path: configs/crypto-config/orgs/org1/admin/tls/server.key
    signedCert:
      path: configs/crypto-config/orgs/org1/admin/tls/server.crt
  org2:
    mspid: org2MSP
    peers: 
      - peer1.org2.deevo.io
    certificateAuthorities:
      - rca.org2.deevo.io
    adminPrivateKey:
      path: configs/crypto-config/orgs/org2/admin/tls/server.key
    signedCert:
      path: configs/crypto-config/orgs/org2/admin/tls/server.crt
  org3:
    mspid: org3MSP
    peers: 
      - peer1.org3.deevo.io
    certificateAuthorities:
      - rca.org3.deevo.io
    adminPrivateKey:
      path: configs/crypto-config/orgs/org3/admin/tls/server.key
    signedCert:
      path: configs/crypto-config/orgs/org3/admin/tls/server.crt
  org4:
    mspid: org4MSP
    peers: 
      - peer1.org4.deevo.io
    certificateAuthorities:
      - rca.org4.deevo.io
    adminPrivateKey:
      path: configs/crypto-config/orgs/org4/admin/tls/server.key
    signedCert:
      path: configs/crypto-config/orgs/org4/admin/tls/server.crt
  org5:
    mspid: org5MSP
    peers: 
      - peer1.org5.deevo.io
    certificateAuthorities:
      - rca.org5.deevo.io
    adminPrivateKey:
      path: configs/crypto-config/orgs/org5/admin/tls/server.key
    signedCert:
      path: configs/crypto-config/orgs/org5/admin/tls/server.crt

orderers:
  orderer1.org0.deevo.io:
    url: grpcs://orderer1.org0.deevo.io:7050
    grpcOptions:
      ssl-target-name-override: orderer1.org0.deevo.io
      grpc-keepalive-timeout-ms: 3000
      grpc.keepalive_time_ms: 360000
      grpc-max-send-message-length: 10485760
      grpc-max-receive-message-length: 10485760
    tlsCACerts:
      path: configs/crypto-config/orgs/org0/msp/tlscacerts/tls-rca-org0-deevo-io-7054.pem
peers:
  peer1.org1.deevo.io:
    url: grpcs://peer1.org1.deevo.io:7051
    eventUrl: grpcs://peer1.org1.deevo.io:7053
    grpcOptions:
      ssl-target-name-override: peer1.org1.deevo.io
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: configs/crypto-config/orgs/org1/msp/tlscacerts/tls-rca-org1-deevo-io-7054.pem
  peer1.org2.deevo.io:
    url: grpcs://peer1.org2.deevo.io:7051
    eventUrl: grpcs://peer1.org2.deevo.io:7053
    grpcOptions:
      ssl-target-name-override: peer1.org2.deevo.io
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: configs/crypto-config/orgs/org2/msp/tlscacerts/tls-rca-org2-deevo-io-7054.pem
  peer1.org3.deevo.io:
    url: grpcs://peer1.org3.deevo.io:7051
    eventUrl: grpcs://peer1.org3.deevo.io:7053
    grpcOptions:
      ssl-target-name-override: peer1.org3.deevo.io
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: configs/crypto-config/orgs/org3/msp/tlscacerts/tls-rca-org3-deevo-io-7054.pem
  peer1.org4.deevo.io:
    url: grpcs://peer1.org4.deevo.io:7051
    eventUrl: grpcs://peer1.org4.deevo.io:7053
    grpcOptions:
      ssl-target-name-override: peer1.org4.deevo.io
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: configs/crypto-config/orgs/org4/msp/tlscacerts/tls-rca-org4-deevo-io-7054.pem
  peer1.org5.deevo.io:
    url: grpcs://peer1.org5.deevo.io:7051
    eventUrl: grpcs://peer1.org5.deevo.io:7053
    grpcOptions:
      ssl-target-name-override: peer1.org5.deevo.io
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: configs/crypto-config/orgs/org5/msp/tlscacerts/tls-rca-org5-deevo-io-7054.pem

certificateAuthorities:
  rca.org0.deevo.io:
    url: https://rca.org0.deevo.io:7054
    httpOptions:
      verify: false
    tlsCACerts:
      path: configs/crypto-config/ca/tls.rca.org0.deevo.io.pem
    registrar:
      - enrollId: rca-org0-admin
        enrollSecret: rca-org0-adminpw
    caName: rca.org0.deevo.io
  rca.org1.deevo.io:
    url: https://rca.org1.deevo.io:7054
    httpOptions:
      verify: false
    tlsCACerts:
      path: configs/crypto-config/ca/tls.rca.org1.deevo.io.pem
    registrar:
      - enrollId: rca-org1-admin
        enrollSecret: rca-org1-adminpw
    caName: rca.org1.deevo.io
  rca.org2.deevo.io:
    url: https://rca.org2.deevo.io:7054
    httpOptions:
      verify: false
    tlsCACerts:
      path: configs/crypto-config/ca/tls.rca.org2.deevo.io.pem
    registrar:
      - enrollId: rca-org2-admin
        enrollSecret: rca-org2-adminpw
    caName: rca.org2.deevo.io
  rca.org3.deevo.io:
    url: https://rca.org3.deevo.io:7054
    httpOptions:
      verify: false
    tlsCACerts:
      path: configs/crypto-config/ca/tls.rca.org3.deevo.io.pem
    registrar:
      - enrollId: rca-org3-admin
        enrollSecret: rca-org3-adminpw
    caName: rca.org3.deevo.io
  rca.org4.deevo.io:
    url: https://rca.org4.deevo.io:7054
    httpOptions:
      verify: false
    tlsCACerts:
      path: configs/crypto-config/ca/tls.rca.org4.deevo.io.pem
    registrar:
      - enrollId: rca-org4-admin
        enrollSecret: rca-org4-adminpw
    caName: rca.org4.deevo.io
  rca.org5.deevo.io:
    url: https://rca.org5.deevo.io:7054
    httpOptions:
      verify: false
    tlsCACerts:
      path: configs/crypto-config/ca/tls.rca.org5.deevo.io.pem
    registrar:
      - enrollId: rca-org5-admin
        enrollSecret: rca-org5-adminpw
    caName: rca.org5.deevo.io
